name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 10
      - run: npm ci
      - run: npm run prettier:lint
      - run: npm run schema:lint
      - run: npm run events:lint

  build:
    runs-on: ubuntu-latest

    needs: lint

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build
        env:
          CI: true
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - run: npm ci
      - shell: bash
        env:
          TW_CALC_API_KEY: ${{ secrets.TW_CALC_API_KEY }}
        run: npm run deploy -- "$TW_CALC_API_KEY"
