name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run prettier:lint

  schema:
    runs-on: ubuntu-latest

    needs: lint

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run schema:lint

  build:
    runs-on: ubuntu-latest

    needs: schema

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build
        env:
          CI: true
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: build
